### ISSUE TITLE
エラー：データの追加失敗（Test_Server.cs）

### ISSUE THREAD

**Issue by ta-hayashi** [ta-hayashi/Test_communication#1]
ファイル：Test_Server.cs
行数：108
エラー	CS1503	
　　　　引数 1: は 'byte[]' から 'byte' へ変換することはできません。

受け取るデータを一時的にリストに格納→定義を予定しております。
この格納時の「データをリストに追加していく」作業でつまずいています。

**Comment by roboshin** [comment]
getDataをgetData[0]に変更
getDataは、長さが1の配列なので、List<byte>に対してはgetData[0]となる

**Comment by f-frhs** [comment]
C# Interactive ウィンドウにて、
```
> var bytelist = new List<byte>();
> Print(bytelist);
List<byte>(0) { }
> bytelist.Add(2);   // 1要素のバイトを追加した
> Print(bytelist);
List<byte>(1) { 2 }
> var list = new byte[] { 1, 2 };
> Print(list);
byte[2] { 1, 2 }
> bytelist.Add(list);  // 2要素のバイト配列を追加してみる
(1,14): error CS1503: 引数 1: は 'byte[]' から 'byte' へ変換することはできません。
> 
```

**Comment by ta-hayashi** [comment]
getDataをgetData[0]に変更
を行いましたが実行結果が意図したものではなかったため、データの送信部を見直します。
現状：Listの2行目の送信がおこなえていない模様

**Comment by roboshin** [comment]
greeting = stringList[0]; // キャスト不要
        byte[] Gdata = System.Text.Encoding.UTF8.GetBytes(greeting);
             // 各要素の列挙
             foreach (string str in stringList)
             {
                 Console.WriteLine(str);
             }
        ns.Write(Gdata,0, Gdata.Length);
greetingのみ送信しているので、サーバー側には”こんにちは”のみ送信しています。
