### ISSUE TITLE
コメント・関数名の修正

### ISSUE THREAD

**Issue by ta-hayashi** [ta-hayashi/Test_communication#3]
要修正ポイント：
コメント・関数名の修正
WritLineｎの運用統一
List送受信でstringを介しているので直接intで行う

修正？
Main内で接続設定をインスタンスしている件（newを使わずに同様の動作をさせる）

**Comment by f-frhs** [comment]
4つの箇所を表すのに、 4つの issue を作成したほうが好ましいと思います。
個別のコメントをしやすいからです。
